title: Quantum Materials Simulation Research
url: https://quantum-materials-simulation-research.github.io
email: nara.moraes@usp.br
description: ''
skills: ''
meta_author: Moraes Nara
google_verify: null
bing_verify: null
contact: static
disqus_shortname: myshortname
color:
  primary: 80B3FF
  primary-rgb: 128,179,255
  secondary: 2c3e50
  secondary-dark: e3dad4
footer:
  copyright: Nara √Åvila Moraes
social: null
markdown: kramdown
permalink: pretty
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: ''
org: quantum-materials-simulation-research
utm_source: quantum-materials-simulation-research
github_url: https://github.com/quantum-materials-simulation-research/quantum-materials-simulation-research.github.io
ga_tracking_id: G-BS975FKGYZ
hero_image: /img/hero-banner.jpg
